<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "pedidos".
 *
 * @property integer $id
 * @property integer $id_user
 * @property integer $id_mesa
 * @property integer $id_estado
 * @property string $data_pedido
 * @property string $hora_pedido
 *
 * @property Fatura[] $faturas
 * @property User $idUser
 * @property Mesa $idMesa
 * @property Estado $idEstado
 * @property PedidosEmArtigo[] $pedidosEmArtigos
 * @property Artigo[] $idArtigos
 */
class Pedidos extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pedidos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'id_mesa', 'id_estado', 'hora_pedido'], 'required'],
            [['id_user', 'id_mesa', 'id_estado'], 'integer'],
            [['data_pedido'], 'safe'],
            [['hora_pedido'], 'string', 'max' => 10],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id']],
            [['id_mesa'], 'exist', 'skipOnError' => true, 'targetClass' => Mesa::className(), 'targetAttribute' => ['id_mesa' => 'id']],
            [['id_estado'], 'exist', 'skipOnError' => true, 'targetClass' => Estado::className(), 'targetAttribute' => ['id_estado' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'id_mesa' => 'Id Mesa',
            'id_estado' => 'Id Estado',
            'data_pedido' => 'Data Pedido',
            'hora_pedido' => 'Hora Pedido',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFaturas()
    {
        return $this->hasMany(Fatura::className(), ['id_pedidos' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdMesa()
    {
        return $this->hasOne(Mesa::className(), ['id' => 'id_mesa']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdEstado()
    {
        return $this->hasOne(Estado::className(), ['id' => 'id_estado']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPedidosEmArtigos()
    {
        return $this->hasMany(PedidosEmArtigo::className(), ['id_pedidos' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdArtigos()
    {
        return $this->hasMany(Artigo::className(), ['id' => 'id_artigo'])->viaTable('pedidos_em_artigo', ['id_pedidos' => 'id']);
    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        //Obter dados do registo em causa
        $id=$this->id;
        $id_user=$this->id_user;
        $id_mesa=$this->id_mesa;
        $id_estado=$this->id_estado;
        $data_pedido=$this->data_pedido;
        $hora_pedido = $this->hora_pedido;
        if($id_estado == 1){

        $myObj=new \stdClass();
        $myObj->id=$id;
        $myObj->id_user=$id_user;
        $myObj->id_mesa=$id_mesa;
        $myObj->id_estado=$id_estado;
        $myObj->data_pedido=$data_pedido;
        $myObj->hora_pedido=$hora_pedido;   

        $myJSON = json_encode($myObj);

            $this->FazPublish("PEDIDO FEITO",$myJSON);
        }
    }

    public function FazPublish($canal, $msg){
        $server = "127.0.0.1";
        $port = 1883;
        $username = ""; // set your username
        $password = ""; // set your password
        $client_id = "phpMQTT-publisher"; // unique!
        $mqtt = new \common\mosquitto\phpMQTT($server, $port, $client_id);
        if ($mqtt->connect(true, NULL, $username, $password))
        {
            $mqtt->publish($canal, $msg, 0);
            $mqtt->close();
        }
        else{
           file_put_contents("debug.output"."Timeout!");
        }
    }
}

